# -*- coding: utf-8 -*-
"""Project Phase2 v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G71EKvYBS5kKNt_47aN1Wh--GgbOUdR0
"""

!pip install google-api-python-client

!pip install pytest

from apiclient.discovery import build
import requests

from google.colab import drive
drive.mount('/content/gdrive')

api_key = "AIzaSyBp1My9BZ8LWl6SxgcMl4TalB3IAebv37E"
cse_id = '9249d3137d5084d51'

resource = build("customsearch", 'v1', developerKey=api_key).cse()

product_categories = ["Wall Ovens","Kitchen Cabinets","Stoves","Mixing Bowls","Garbage Disposals","Woks","Toaster Ovens","Iron Skillets","Frying Pans","Kitchen Shears"]
len(product_categories)

for j in product_categories:
  c = 0
  images = []
  for i in range(1, 10, 10):
      result = resource.list(q=j, cx=cse_id,
                        searchType='image', start=i).execute()
      images += result['items']
  for item in images:
    c = c+1
    r = requests.get(item['link'],stream = True)
    with open("/content/gdrive/My Drive/CS634Project/"+j+"_"+str(c)+".png","wb") as file:
      for block in r.iter_content(chunk_size = 1024):
        if block:
          file.write(block)

data_path = "/content/gdrive/MyDrive/CS634Project"
from IPython import display
import os

file_list = list(os.listdir(data_path))

import cv2
from matplotlib import pyplot as plt

"""### Displaying Images"""

image_files = []
for i in file_list:
  image_files.append(cv2.imread(data_path+"/"+i))



fig = plt.figure(figsize=(20, 100))
  
# setting values to rows and column variables
rows = 20
columns = 5
fig.add_subplot(rows, columns, 1)

for i in range(1,101):
  fig.add_subplot(rows, columns, i)
  plt.imshow(image_files[i-1])
  plt.axis('off')
  plt.title("Image")